#!/bin/bash
# RSP 2010-09-16
echo
echo "Forked - Copyright (c) 2010 Rafal Pocztarski"
echo "This program comes with ABSOLUTELY NO WARRANTY."
echo "You may redistribute it under certain conditions."
echo "See LICENSE for details."
echo
echo "Forked clones your forked version of a github repository"
echo "using conventions from: http://help.github.com/forking/"
echo "Project home page: http://github.com/rsp/forked"
echo
me=`git config github.user || whoami`
user=$1
repo=$2
if [ "$repo" == "" ]; then
    echo "Usage: forked USER REPOSITORY"
    echo
    echo "Clones repository:"
    echo "    git@github.com:YOU/REPOSITORY.git"
    echo "and adds upstream remote:"
    echo "    git://github.com/USER/REPOSITORY.git"
    echo
    echo "You have to fork it on github first using the Fork button on:"
    echo "    http://github.com/USER/REPOSITORY"
    echo "and set your github username using:"
    echo "    git config --global github.user USERNAME"
    echo "if it is different than your local login name."
    echo
    echo "Your github username is set to: $me"
    echo
    exit 1
fi
origin=git@github.com:$me/$repo.git
upstream=git://github.com/$user/$repo.git
echo "Your github username is set to: $me"
echo "Forked is going to clone:"
echo "    $origin"
echo "and add remote upstream:"
echo "    $upstream"
echo
git clone $origin && \
cd $repo && \
git remote add upstream $upstream && \
git fetch upstream && \
echo -e "\nForked: DONE" || (echo -e "\nForked: ERROR"; exit 2)

